# It seems that docker-compose won't really help us since we need to launch
# containers from within containers. Unless DC gives us some method to
# dynamically launch containers...but that seems unlikely.

version: '2.2'

services:

  client:
    user: root
    build: client
    init: true
    container_name: aio-client
    restart: on-failure
    deends_on:
      - server

  server:
    user: nobody
    build: server
    init: true
    container_name: abingham/aio-server
    restart: on-failure
