version: '2.2'
networks:
  default:
    external:
      name: aio

services:
  client:
    build:
      context: client
    user: root
    init: true
    image: abingham/aio-client
    container_name: aio-client
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build:
      context: server
    user: root
    init: true
    image: abingham/aio-server
    container_name: aio-server
    restart: "no"
    ports:
      - 4647:4647
